# Generated by Django 6.0.3 on 2026-03-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на описание (URL)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='manual',
            field=models.FileField(blank=True, upload_to='manuals/%Y/%m/%d', verbose_name='Инструкция по уходу (PDF)'),
        ),
    ]
