# Generated by Django 6.0.3 on 2026-03-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_tag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='plants',
            field=models.ManyToManyField(blank=True, related_name='articles', to='store.plant', verbose_name='Связанные растения'),
        ),
    ]
