# Generated by Django 6.0.3 on 2026-03-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_article_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='plants', to='store.tag', verbose_name='Теги'),
        ),
    ]
